### ISSUE TITLE
Hilos 

### ISSUE THREAD

**Issue by garaudy12** [SistemasTecTlaxiaco/practica-de-hilos-garaudy12#2]
[Hilos - Solano Mendoza Taoli Garaudy.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-garaudy12/files/6519725/Hilos.-.Solano.Mendoza.Taoli.Garaudy.pdf)

**Comment by MLR062998** [comment]
calificación:  18/20
califico: Manuel lopez
faltaron imágenes
buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado
